name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      track:
        description: 'Play Store track'
        required: true
        default: 'alpha'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production
      release_status:
        description: 'Release status'
        required: true
        default: 'draft'
        type: choice
        options:
          - draft
          - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-flutter

      - name: Setup Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: android

      - name: Verify, sign, build, deploy
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          PLAY_STORE_JSON_KEY: ${{ secrets.PLAY_STORE_JSON_KEY }}
          PLAY_STORE_TRACK: ${{ inputs.track || 'alpha' }}
          PLAY_STORE_RELEASE_STATUS: ${{ inputs.release_status || 'completed' }}
        run: just release
